### ISSUE TITLE
Erro ao executar scrape_df(df_plen)

### ISSUE THREAD

**Issue by lflucasferreira** [estadao/bolsonaro-e-ditadura-no-congresso#1]
Já busquei replicar o notebook de diversas maneiras, mas não consegui porque dá um erro com a função exatamente na linha **df.progress_apply(scrape_row_plen, axis = 1)**.

Você poderia, por favor, informar os requisitos de todas as bibliotecas e versões utilizadas?

Utilizei o python3.7 e instalei no Ubuntu 18.04.

Fico no aguardo da sua disposição para me ajudar a replicar o projeto.

Arquivo: **pega-pronunciamentos-html**

**Comment by RodrigoMenegat** [comment]
Caro, pode compartilhar a mensagem de erro?

Sem olhar a fundo, imagino que falte o pacote `tqdm`, que serve só para mensurar o tempo de execução de cada loop.
```
from tqdm._tqdm_notebook import tqdm_notebook as tqdm
```
Você está executando o código em um Jupyter Notebook? Caso contrário, acho que a forma de importar muda um pouco.

Uma alternativa é substituir o *df.progress_apply* por, simplesmente, *df.apply*, que é a função nativa do pandas, sem monitorar o tempo de execução.

Amanhã, quando estiver no trabalho, te passo a configuração exata do ambiente em que executamos o código.

**Comment by lflucasferreira** [comment]
Vê só. 

Tentei em outra máquina e tive o mesmo erro. Não alterei nada do que você implementou. Troquei pro **df.apply** e mesmo assim o erro persistiu. Não faltava a biblioteca tqdm, caso contrário já teria dado erro na primeira linha do notebook, pois ele é importado lá.

Segue o erro que foi exibido ao executar a linha citada na primeira interação deste issue.

> Erro:

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-17-d6565cf183b1> in <module>
----> 1 scrape_df(df_plen)

<ipython-input-15-2c7b2bf44e02> in scrape_df(df)
      9 
     10     if 'Sessão' in df.columns:
---> 11         df.apply(scrape_row_plen, axis = 1)
     12     elif 'Comissão' in df.columns:
     13         df.apply(scrape_row_com, axis = 1)

/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py in apply(self, func, axis, broadcast, raw, reduce, result_type, args, **kwds)
   6485                          args=args,
   6486                          kwds=kwds)
-> 6487         return op.get_result()
   6488 
   6489     def applymap(self, func):

/anaconda3/lib/python3.6/site-packages/pandas/core/apply.py in get_result(self)
    149             return self.apply_raw()
    150 
--> 151         return self.apply_standard()
    152 
    153     def apply_empty_result(self):

/anaconda3/lib/python3.6/site-packages/pandas/core/apply.py in apply_standard(self)
    255 
    256         # compute the result using the series generator
--> 257         self.apply_series_generator()
    258 
    259         # wrap results

/anaconda3/lib/python3.6/site-packages/pandas/core/apply.py in apply_series_generator(self)
    284             try:
    285                 for i, v in enumerate(series_gen):
--> 286                     results[i] = self.f(v)
    287                     keys.append(v.name)
    288             except Exception as e:

<ipython-input-10-cb9e2b60f579> in scrape_row_plen(row)
     19         path = "../data/txts/plenario/"
     20         file_id = [ str(row.name), row.Data, row.Hora, row.Fase, row.Sessão ]
---> 21         save_txt(txt, path, *file_id)
     22 
     23         # time.sleep(.2)

<ipython-input-8-2445f24c8082> in save_txt(content, path, *args)
     10     fname = path + file_id + ".txt"
     11 
---> 12     with open(fname, 'w+') as file:
     13         file.write(content)
     14 

FileNotFoundError: [Errno 2] No such file or directory: '../data/txts/plenario/0-11042019-11h24-ORDEM DO DIA-66-2019.txt'
`

**Comment by RodrigoMenegat** [comment]
Por algum motivo, faltaram duas pastas no repositório, dentro do diretório `../data/txt`, como diz a mensagem de erro. São os subdiretórios `plenario` e `comissao`. Ao tentar criar o arquivo, o script falha porque o caminho não existe. Ainda hoje vou atualizar o repo, mas creio que criar os diretórios manualmente dentro da estrutura clonada deve resolver. 

Sobre o pacote tqdm: caso você use ele em um ambiente que não o Jupyter, ele precisa ser importado de outra maneira - a importação não falharia, mas haveria um possível erro na execução. Como você mostrou, porém, não é isso que causa o erro. O problema acontece na função que salva o arquivo, é mais simples :)

**Comment by RodrigoMenegat** [comment]
Caro, acabei de alterar a estrutura do repositório. Coloquei dois arquivos `PLACEHOLDER` para que o GitHub reconhecesse os diretórios faltantes, então ele deve funcionar caso você clone novamente. Testei aqui no nosso ambiente e tudo rolou conforme previsto. 

Imagino que apenas criar esses diretórios resolva o problema, mas também criei um arquivo [`REQUIREMENTS.txt`](https://github.com/estadao/bolsonaro-e-ditadura-no-congresso/blob/master/REQUIREMENTS.txt) que lista os pacotes e versões utilizadas. O sistema operacional no qual testei é macOS 10.14.

Pode verificar se o problema foi resolvido, por favor?

**Comment by lflucasferreira** [comment]
Sim, foi resolvido. Grato!
